# Generated by Django 4.1.13 on 2024-02-06 15:50

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='articulos')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.articulo')),
            ],
        ),
    ]
