# Generated by Django 4.1.13 on 2024-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_articulo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
